// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LoginImport } from "./routes/login"
import { Route as LayoutRouteImport } from "./routes/_layout/route"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as LayoutRepositoriesRouteImport } from "./routes/_layout/repositories/route"
import { Route as LayoutPrsIndexImport } from "./routes/_layout/prs/index"
import { Route as LayoutPrsCommitsRouteImport } from "./routes/_layout/prs/commits/route"
import { Route as LayoutPrsPrIdRouteImport } from "./routes/_layout/prs/$prId/route"

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: "/",
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutRepositoriesRouteRoute = LayoutRepositoriesRouteImport.update({
  path: "/repositories",
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutPrsIndexRoute = LayoutPrsIndexImport.update({
  path: "/prs/",
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutPrsCommitsRouteRoute = LayoutPrsCommitsRouteImport.update({
  path: "/prs/commits",
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutPrsPrIdRouteRoute = LayoutPrsPrIdRouteImport.update({
  path: "/prs/$prId",
  getParentRoute: () => LayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_layout/repositories": {
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    "/_layout/": {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    "/_layout/prs/$prId": {
      preLoaderRoute: typeof LayoutPrsPrIdRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    "/_layout/prs/commits": {
      preLoaderRoute: typeof LayoutPrsCommitsRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    "/_layout/prs/": {
      preLoaderRoute: typeof LayoutPrsIndexImport
      parentRoute: typeof LayoutRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRouteRoute.addChildren([
    LayoutRepositoriesRouteRoute,
    LayoutIndexRoute,
    LayoutPrsPrIdRouteRoute,
    LayoutPrsCommitsRouteRoute,
    LayoutPrsIndexRoute,
  ]),
  LoginRoute,
])
